export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'

//spinner
export const SET_SPINNER_ON = 'SET_SPINNER_ON'
export const SET_SPINNER_OFF = 'SET_SPINNER_OFF'

//util
export const SET_BOOKING_STEP_VALUE = 'SET_BOOKING_STEP_VALUE'

//productItem
export const SET_PRODUCT_ITEM_ATTRIBUTES_VALUES = 'SET_PRODUCT_ITEM_ATTRIBUTES'
