export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'

//spinner
export const SET_SPINNER_ON = 'SET_SPINNER_ON'
export const SET_SPINNER_OFF = 'SET_SPINNER_OFF'

//util
export const SET_BOOKING_STEP_VALUE = 'SET_BOOKING_STEP_VALUE'


//productItem
export const SET_PRODUCT_ITEM_ATTRIBUTES_VALUES = 'SET_PRODUCT_ITEM_ATTRIBUTES'
export const SET_BOOKING_PRICE_VALUE = 'SET_BOOKING_PRICE_VALUE'
export const SET_PRODUCT_ITEM_ID = 'SET_PRODUCT_ITEM_ID'
export const SET_DRIVER = 'SET_DRIVER'
export const SET_MONEY_PAID_ONLINE = 'SET_MONEY_PAID_ONLINE'
export const SET_MONEY_PAID_ONLINE_LINE_THROUGH = 'SET_MONEY_PAID_ONLINE_LINE_THROUGH'
//booking 
export const SET_BOOKING_DATES =  'SET_BOOKING_DATES'
export const SET_PICKUP_TIME =  'SET_PICKUP_TIME'
export const SET_RETURN_TIME =  'SET_RETURN_TIME'
export const SET_PICKUP_LOCATION =  'SET_PICKUP_LOCATION'
export const SET_RETURN_LOCATION =  'SET_RETURN_LOCATION'